### ISSUE TITLE
about test the result file 

### ISSUE THREAD

**Issue by JiangWeiHn** [Epiphqny/SOLOv2#22]
![image](https://user-images.githubusercontent.com/24561984/84343237-2af2d900-abda-11ea-9d47-565702aae228.png)
please help me ,when I run my dataset with the test_ins.py ,I got the disorderly code in segmentation,finally,I got the error:

Traceback (most recent call last):
  File "tools/test_ins.py", line 257, in <module>
    main()
  File "tools/test_ins.py", line 235, in main
    coco_eval(result_files, eval_types, dataset.coco)
  File "/home/JW/SOLOv2-bladder/mmdet/core/evaluation/coco_utils.py", line 49, in coco_eval
    cocoEval.evaluate()
  File "/home/software/anaconda3/envs/torch/lib/python3.7/site-packages/pycocotools/cocoeval.py", line 141, in evaluate
    self._prepare()
  File "/home/software/anaconda3/envs/torch/lib/python3.7/site-packages/pycocotools/cocoeval.py", line 106, in _prepare
    _toMask(dts, self.cocoDt)
  File "/home/software/anaconda3/envs/torch/lib/python3.7/site-packages/pycocotools/cocoeval.py", line 93, in _toMask
    rle = coco.annToRLE(ann)
  File "/home/software/anaconda3/envs/torch/lib/python3.7/site-packages/pycocotools/coco.py", line 430, in annToRLE
    rles = maskUtils.frPyObjects(segm, h, w)
  File "pycocotools/_mask.pyx", line 298, in pycocotools._mask.frPyObjects
  File "pycocotools/_mask.pyx", line 278, in pycocotools._mask.frUncompressedRLE
ValueError: invalid literal for int() with base 10: 'm2S;W61M6L8H6I5L4K4M3L4M2N2N2N1O1O1O2N1O1O2N1O2O0O1O2N1O101N1O2O000O1O2N1O1O1O1O2N1O1O2N2O2M3M4L2N3N1N2O1O1N101N2O001N10001N101O1N1O2O1N2N2O1N1O2O0O2O1N101N2O0O2O1N1O2O0O100O101N10000O100O10000O10000

**Comment by JiangWeiHn** [comment]
it is my fault,somebody change the pycocotools,I have no problem

**Comment by HCShi** [comment]
I have also met the problem, could you please share the solutions?

**Comment by Benoi-mos** [comment]
sorry how did you solve this? I'm experiencing the same error!
