### ISSUE TITLE
inference error

### ISSUE THREAD

**Issue by deep-practice** [Epiphqny/SOLOv2#25]
I use the pretrained weight to infer,but got the following error:

Traceback (most recent call last):
  File "inference_demo.py", line 15, in <module>
    show_result(img, result, model.CLASSES, score_thr=0.25, out_file="demo_out.jpg")
  File "/home/work/deep_learning/instance_segmentation/SOLOv2/mmdet/apis/inference.py", line 154, in show_result
    for i, bbox in enumerate(bbox_result)
  File "/home/work/deep_learning/instance_segmentation/SOLOv2/mmdet/apis/inference.py", line 154, in <listcomp>
    for i, bbox in enumerate(bbox_result)
AttributeError: 'tuple' object has no attribute 'shape'

the inference code I use is modified from  inference_demo.ipynb
pls,I can train normally.

**Comment by YuqingWang1029** [comment]
@deep-practice The code of demo is copied from the SOLO v1 code and I haven't used the code, you could run the test code to see if it is correct.

**Comment by deep-practice** [comment]
Test is ok.
