### ISSUE TITLE
TypeError: object of type 'int' has no len()

### ISSUE THREAD

**Issue by RoterDL** [Epiphqny/SOLOv2#6]
我将COCO数据集的相关输入更改为了自己的训练集的相关参数，会有如下报错：
`2020-04-15 15:25:19,647 - mmdet - INFO - Distributed training: False
2020-04-15 15:25:19,647 - mmdet - INFO - MMDetection Version: 1.0.0+unknown
2020-04-15 15:25:19,647 - mmdet - INFO - Config:
# model settings
model = dict(
    type='SOLO',
    pretrained='torchvision://resnet50',
    backbone=dict(
        type='ResNet',
        depth=50,
        num_stages=4,
        out_indices=(0, 1, 2, 3),  # C2, C3, C4, C5
        frozen_stages=1,
        style='pytorch'),
    neck=dict(
        type='FPN',
        in_channels=[256, 512, 1024, 2048],
        out_channels=256,
        start_level=0,
        num_outs=5),
    bbox_head=dict(
        type='SOLOV2Head',
        # 绫诲埆
        num_classes=35,
        in_channels=256,
        stacked_convs=7,
        seg_feat_channels=256,
        strides=[8, 8, 16, 32, 32],
        scale_ranges=((1, 96), (48, 192), (96, 384), (192, 768), (384, 2048)),
        sigma=0.2,
        num_grids=[40, 36, 24, 16, 12],
        cate_down_pos=0,
        with_deform=False,
        loss_ins=dict(
            type='DiceLoss',
            use_sigmoid=True,
            loss_weight=3.0),
        loss_cate=dict(
            type='FocalLoss',
            use_sigmoid=True,
            gamma=2.0,
            alpha=0.25,
            loss_weight=1.0),
    ))
# training and testing settings
train_cfg = dict()
test_cfg = dict(
    nms_pre=500,
    score_thr=0.1,
    mask_thr=0.5,
    update_thr=0.05,
    kernel='gaussian',  # gaussian/linear
    sigma=2.0,
    max_per_img=100)
# dataset settings
dataset_type = 'CocoDataset'
custom_data = 'D:\\Dataset\\bladder\\bladder_20200402\\'
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True, with_mask=True),
    dict(type='Resize',
         img_scale=[(1333, 800), (1333, 768), (1333, 736),
                    (1333, 704), (1333, 672), (1333, 640)],

         multiscale_mode='value',
         keep_ratio=True),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels', 'gt_masks']),
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(1333, 800),

        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='Pad', size_divisor=32),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
]

data = dict(
    imgs_per_gpu=2,
    workers_per_gpu=2,
    train=dict(
        type=dataset_type,
        ann_file=custom_data + 'annotations\\train.json',
        img_prefix=custom_data + 'image\\',
        pipeline=train_pipeline),
    val=dict(
        type=dataset_type,
        ann_file=custom_data + 'annotations\\val.json',
        img_prefix=custom_data + 'image\\',
        pipeline=test_pipeline),
    test=dict(
        type=dataset_type,
        ann_file=custom_data + 'annotations\\val.json',
        img_prefix=custom_data + 'image\\',
        pipeline=test_pipeline))
# optimizer
optimizer = dict(type='SGD', lr=0.01, momentum=0.9, weight_decay=0.0001)
optimizer_config = dict(grad_clip=dict(max_norm=35, norm_type=2))
# learning policy
lr_config = dict(
    policy='step',
    warmup='linear',
    warmup_iters=500,
    warmup_ratio=1.0 / 3,
    step=[27, 33])
checkpoint_config = dict(interval=1)
# yapf:disable
log_config = dict(
    interval=50,
    hooks=[
        dict(type='TextLoggerHook'),
        # dict(type='TensorboardLoggerHook')
    ])
# yapf:enable
# runtime settings
total_epochs = 36
device_ids = range(8)
dist_params = dict(backend='nccl')
log_level = 'INFO'
work_dir = './work_dirs/solo_r50_3x'
load_from = None
resume_from = None
workflow = [('train', 1)]

2020-04-15 15:25:20,054 - mmdet - INFO - load model from: torchvision://resnet50
2020-04-15 15:25:20,316 - mmdet - WARNING - The model and loaded state dict do not match exactly

unexpected key in source state_dict: fc.weight, fc.bias

loading annotations into memory...
Done (t=0.30s)
creating index...
index created!
2020-04-15 15:25:22,619 - mmdet - INFO - Start running, host: Administrator@SC-202003270809, work_dir: D:\workspace\SOLO\SOLOv2-master\tools\work_dirs\solo_r50_3x
2020-04-15 15:25:22,619 - mmdet - INFO - workflow: [('train', 1)], max: 36 epochs
Traceback (most recent call last):
  File "D:/workspace/SOLO/SOLOv2-master/tools/train.py", line 125, in <module>
    main()
  File "D:/workspace/SOLO/SOLOv2-master/tools/train.py", line 121, in main
    timestamp=timestamp)
  File "D:\workspace\SOLO\SOLOv2-master\mmdet\apis\train.py", line 111, in train_detector
    timestamp=timestamp)
  File "D:\workspace\SOLO\SOLOv2-master\mmdet\apis\train.py", line 297, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "C:\ProgramData\Anaconda3\envs\torch\lib\site-packages\mmcv\runner\runner.py", line 364, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "C:\ProgramData\Anaconda3\envs\torch\lib\site-packages\mmcv\runner\runner.py", line 264, in train
    for i, data_batch in enumerate(data_loader):
  File "C:\ProgramData\Anaconda3\envs\torch\lib\site-packages\torch\utils\data\dataloader.py", line 345, in __next__
    data = self._next_data()
  File "C:\ProgramData\Anaconda3\envs\torch\lib\site-packages\torch\utils\data\dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "C:\ProgramData\Anaconda3\envs\torch\lib\site-packages\torch\utils\data\dataloader.py", line 881, in _process_data
    data.reraise()
  File "C:\ProgramData\Anaconda3\envs\torch\lib\site-packages\torch\_utils.py", line 394, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\torch\lib\site-packages\torch\utils\data\_utils\worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\ProgramData\Anaconda3\envs\torch\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\ProgramData\Anaconda3\envs\torch\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\workspace\SOLO\SOLOv2-master\mmdet\datasets\custom.py", line 131, in __getitem__
    data = self.prepare_train_img(idx)
  File "D:\workspace\SOLO\SOLOv2-master\mmdet\datasets\custom.py", line 144, in prepare_train_img
    return self.pipeline(results)
  File "D:\workspace\SOLO\SOLOv2-master\mmdet\datasets\pipelines\compose.py", line 24, in __call__
    data = t(data)
  File "D:\workspace\SOLO\SOLOv2-master\mmdet\datasets\pipelines\loading.py", line 106, in __call__
    results = self._load_masks(results)
  File "D:\workspace\SOLO\SOLOv2-master\mmdet\datasets\pipelines\loading.py", line 86, in _load_masks
    gt_masks = [self._poly2mask(mask, h, w) for mask in gt_masks]
  File "D:\workspace\SOLO\SOLOv2-master\mmdet\datasets\pipelines\loading.py", line 86, in <listcomp>
    gt_masks = [self._poly2mask(mask, h, w) for mask in gt_masks]
  File "D:\workspace\SOLO\SOLOv2-master\mmdet\datasets\pipelines\loading.py", line 71, in _poly2mask
    rles = maskUtils.frPyObjects(mask_ann, img_h, img_w)
  File "pycocotools\_mask.pyx", line 292, in pycocotools._mask.frPyObjects
TypeError: object of type 'int' has no len()`

我自己的数据集是按照COCO数据集标准来的，可以读取图片和对应MASK，请问您遇到过这样的情况吗，这个项目适用于训练自己的数据集吗，谢谢！

**Comment by Epiphqny** [comment]
@RoterDL 根据self._poly2mask(mask, h, w) for mask in gt_masks]这里报错，看起来像是polygen转mask的时候出现了问题，coco提供的标注是polygen格式，在代码里转成的binary mask。你可能需要再详细看一下mmdet和coco数据构造的代码，我也没有用自己的数据集训练过，所以也不太清楚。或者你可以尝试试试https://github.com/spytensor/prepare_detection_dataset这个转换工具，但是能否成功我也不好保证哈
